apiVersion: v1
kind: Service
metadata:
  name: ee-service
  labels:
    app: ee-api
  namespace: ee
spec:
  selector:
    matchLabels: ee-api  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
